name: CI

on:
  push:
  pull_request:
  merge_group:

  # run the pipeline on the 0th minute of the 0th hour of day 1 and 15 every month
  schedule:
    - cron: '0 0 1,15 * *'

  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Install dependencies
        run: |
          uv sync --extra test --extra milp

      - name: Run tests
        run: |
          NUMBA_DISABLE_JIT=1 uv run coverage run -m pytest -v -s

      - name: Run Coveralls
        if: ${{ success() }}
        run: |
          uv run coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
